version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:11.15.0-stretch
    working_directory: /conu

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Installing packages...
          command: npm ci
      - run:
          name: Running tests...
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
          environment:
              JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit

  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Installing packages...
          command: npm ci
      - run:
          name: Building the game...
          command: npm run build

  deploy:
    executor: node
    steps:
      - checkout
      - run:
          name: Installing packages...
          command: npm ci
      - run:
          name: Building the game...
          command: npm run deploy -- --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  test:
    jobs:
      - test
      - build
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
            tags:
              only: /v.*/

