version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - checkout
      - run:
          name: Installig packages...
          command: npm ci
      - run:
          name: Running tests...
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
          environment:
              JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit

  build:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - checkout
      - run:
          name: Installig packages...
          command: npm ci
      - run:
          name: Building the game...
          command: npm run build

workflows:
  version: 2
  test:
    jobs:
      - build
      - test

