version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.15.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: npm ci
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Running tests
          command: npm run test
      - store_artifacts:
          path: test-reports/
          destination: jest

